name: Build

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review
        paths-ignore:
            - "**.md"
    workflow_dispatch:
        inputs:
            build_android:
                description: "Build Android"
                required: false
                default: true
                type: boolean
            tag:
                description: "tag"
                required: false
                default: ""
                type: string

jobs:
    android:
        if: ${{ github.event_name == 'pull_request' || github.event.inputs.build_android == 'true' }}
        name: Release Android
        runs-on: ubuntu-latest
        permissions: write-all
        timeout-minutes: 60 

        steps:
            - name: 代码迁出
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: 构建Java环境
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu"
                  java-version: "17"
                  cache: "gradle"

            - name: 安装Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version-file: pubspec.yaml
                  cache: true

            - name: Apply bottom sheet patch
              working-directory: ${{ env.FLUTTER_ROOT }}
              run: git apply $GITHUB_WORKSPACE/lib/scripts/bottom_sheet_patch.diff
              continue-on-error: true

            - name: Write key
              if: github.event_name == 'workflow_dispatch'
              run: |
                  if [ ! -z "${{ secrets.SIGN_KEYSTORE_BASE64 }}" ]; then
                    echo "${{ secrets.SIGN_KEYSTORE_BASE64 }}" | base64 --decode > android/app/key.jks
                    echo storeFile='key.jks' >> android/key.properties
                    echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> android/key.properties
                    echo keyAlias='${{ secrets.KEY_ALIAS }}' >> android/key.properties
                    echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> android/key.properties
                  fi

            - name: Extract version from pubspec.yaml
              id: version
              run: |
                  VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | sed 's/+.*//')
                  BUILD=$(grep '^version:' pubspec.yaml | sed 's/.*+//')
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
                  echo "build=$BUILD" >> $GITHUB_OUTPUT
                  echo "Version: $VERSION, Build: $BUILD"

            - name: Flutter doctor
              run: flutter doctor -v

            - name: Get dependencies
              run: flutter pub get

            - name: Clean build
              run: flutter clean

            - name: Flutter build apk
              run: |
                  flutter build apk --release \
                    --split-per-abi \
                    --dart-define-from-file=pili_release.json

            - name: Rename APK files
              run: |
                  VERSION="${{ steps.version.outputs.version }}"
                  for file in build/app/outputs/flutter-apk/app-*-release.apk; do
                    if [ -f "$file" ]; then
                      abi=$(echo "$file" | sed -E 's|.*app-(.*)-release\.apk|\1|')
                      mv "$file" "PiliPro_android_${VERSION}_${abi}.apk"
                      echo "Renamed: $file -> PiliPro_android_${VERSION}_${abi}.apk"
                    fi
                  done
                  ls -lh PiliPro_android_*.apk || echo "No APK files found!"

            - name: Release
              if: ${{ github.event.inputs.tag != '' }}
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.event.inputs.tag }}
                  name: ${{ github.event.inputs.tag }}
                  files: |
                      PiliPro_android_*.apk

            - name: Upload arm64-v8a
              uses: actions/upload-artifact@v4
              with:
                  name: Android_arm64-v8a
                  path: PiliPro_android_*_arm64-v8a.apk
                  if-no-files-found: error

            - name: Upload armeabi-v7a
              uses: actions/upload-artifact@v4
              with:
                  name: Android_armeabi-v7a
                  path: PiliPro_android_*_armeabi-v7a.apk
                  if-no-files-found: error

            - name: Upload x86_64
              uses: actions/upload-artifact@v4
              with:
                  name: Android_x86_64
                  path: PiliPro_android_*_x86_64.apk
                  if-no-files-found: warn